In [1]:
import tensorflow as tf

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
message = tf.constant('Welcome to the exciting world of Deep Neural Networks!')

In [4]:
with tf.Session() as sess:
    print(sess.run(message).decode())

Welcome to the exciting world of Deep Neural Networks!


# Addition
addition of two input vectors

In [5]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = tf.add(v_1, v_2)
v_add

<tf.Tensor 'Add:0' shape=(4,) dtype=int32>

In [6]:
with tf.Session() as sess:
    print(sess.run(v_add))

[3 3 8 7]


# Working with constants, variables and placeholders

In [7]:
sess = tf.InteractiveSession()
t_1 = tf.constant(4)
t_2 = tf.constant([4, 3, 2])
zero_t = tf.zeros([2,3], tf.int32)
tf.ones([2,3], tf.int32)
tf.linspace(2.0, 5.0, 5) # add 5 evenly between start and stop
tf.range(10)
tf.random_normal([2,3], mean=2.0, stddev=4, seed=12)
sess.close()


# Variables

In [19]:
sess = tf.InteractiveSession()
rand_t = tf.random_uniform([50, 50], 0, 10, seed=0)
t_a = tf.Variable(rand_t)
t_b = tf.Variable(rand_t)

weights = tf.Variable(tf.random_normal([100,100], stddev=2))
bias = tf.Variable(tf.zeros([100], name='biases'))

initial_op = tf.global_variables_initializer()

sess.close()


# Placeholders

In [20]:
sess = tf.InteractiveSession()

x = tf.placeholder("float")
y = 2 * x
data = tf.random_uniform([4, 5], 10)
x_data = sess.run(data)
print(sess.run(y, feed_dict = {x:x_data}))

sess.close()

[[ 2.774313   6.0191803 19.9714    11.5187845  5.178175 ]
 [18.726     11.8873005  4.2238903  2.2319527 16.274729 ]
 [ 8.805426  10.505729   9.370032  12.434246  19.598211 ]
 [ 6.82707    4.8460293 15.401937  10.6896105 11.493983 ]]


# Performing matrix manipulations

In [22]:
sess = tf.InteractiveSession()

I_matrix = tf.eye(5)
print(I_matrix.eval())

X = tf.Variable(tf.eye(10))
X.initializer.run()

A = tf.Variable(tf.random_normal([5, 10]))
A.initializer.run()

# Multiply matrices
product = tf.matmul(A, X)
print(product.eval())

sess.close()

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 0.11763605  0.35548052  2.3516796   0.22839797 -0.86843884  0.99645644
  -0.45639884  1.2583095   1.3710518   0.11067215]
 [-0.6241576   1.4989452   0.86597663 -1.7951202   0.7798793   0.2382627
  -1.0651782  -0.31821066 -0.16383904 -2.1664476 ]
 [ 0.92024577 -1.2985927  -2.0006142  -2.3996737  -0.90350807  0.598875
  -0.9673578   0.17671104 -1.1204847  -0.3445811 ]
 [ 1.3728462  -0.12288541 -1.4828682  -2.7565014  -0.93281984  0.23274544
  -0.00685087 -0.21985072  0.95627457  0.9908888 ]
 [ 1.1736495   0.205152    0.71666044 -0.18999659  0.29622278 -0.04772888
   0.30904937  1.2644088  -0.74528474 -0.7607406 ]]


In [23]:
sess = tf.InteractiveSession()

sess.close()

# select GPU

In [24]:
config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)


In [30]:
with tf.device('/gpu:0'):
    rand_t = tf.random_uniform([50, 50], 0, 10, dtype=tf.float32, seed=0)
    a = tf.Variable(rand_t)
    b = tf.Variable(rand_t)
    c = tf.matmul(a, b)
    init = tf.global_variables_initializer()
    
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
sess.run(init)
print(sess.run(c))

InvalidArgumentError: Cannot assign a device for operation 'Variable_49': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: Variable_49 = VariableV2[container="", dtype=DT_FLOAT, shape=[50,50], shared_name="", _device="/device:GPU:0"]()]]

Caused by op 'Variable_49', defined at:
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-e8665b2a9723>", line 4, in <module>
    b = tf.Variable(rand_t)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 229, in __init__
    constraint=constraint)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 351, in _init_from_args
    name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 133, in variable_op_v2
    shared_name=shared_name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 1061, in _variable_v2
    shared_name=shared_name, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'Variable_49': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: Variable_49 = VariableV2[container="", dtype=DT_FLOAT, shape=[50,50], shared_name="", _device="/device:GPU:0"]()]]
